repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6  # Use the latest stable version of Ruff
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version of Black
    hooks:
      - id: black

  # Custom local hook to run unit tests before commit
  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        entry: python3 -m unittest -v
        language: system
        pass_filenames: false  # We don't pass filenames to unittest
