name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[examples]"

      - name: Run tests
        run: python -m unittest -v

      - name: Run example scripts
        run: |
          python examples/benchmark.py
          python examples/rrt_panda.py -s 5
          # Not running these scripts for now because they use ruckig to generate a trajectory,
          # and ruckig calls a cloud API if the input has intermediate waypoints
          # (calling this cloud API can be flaky in CI)
          # python examples/position_ctrl.py -s 3
          # python examples/computed_torque_ctrl.py -obs -s 12
